A/A/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('orders/',include('orders.urls',namespace='orders'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

A/accounts/urls.py
from django.urls import path
from accounts import views


app_name = 'accounts'
urlpatterns = [
    path('register/',views.UserRegisterView.as_view(),name='user_register'),
    path('verify/',views.UserRegisterVerifyCode.as_view(),name='verify_code'),
    path('login/',views.UserLoginView.as_view(),name='user_login'),
    path('logout/',views.UserLogoutView.as_view(),name='user_logout'),
]

A/home/urls.py
from django.urls import path,include
from home import views


app_name = 'home'
bucket_urls = [
    path('',views.BucketHomeView.as_view(),name='bucket'),
    path('delete_obj/<str:key>',views.DeleteBucketObjects.as_view(),name='delete_obj_bucket'),
    path('download_obj/<str:key>',views.DownloadBucketObject.as_view(),name='download_obj_bucket'),
    # path('upload_obj/',views.UploadBucketObject.as_view(),name='upload_obj_bucket'),    
]
urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('category/<slug:category_slug>/',views.HomeView.as_view(),name='category_filter'),
    path('bucket/',include(bucket_urls)),
    path('<slug:slug>/',views.ProductDetailView.as_view(),name='product_detail'),
    
    
]

A/orders/urls.py
from django.urls import path
from orders import views


app_name='orders'
urlpatterns = [
    path('create/',views.OrderCreateView.as_view(),name='orders_create'),
    path('detail/<int:order_id>/',views.OrderDetailView.as_view(),name='order_detail'),
    path('cart/',views.CartView.as_view(),name='cart'),
    path('cart/add/<int:product_id>/',views.CartAddView.as_view(),name='cart_add'),
    path('cart/remove/<int:product_id>/',views.CartRemoveView.as_view(),name='cart_remove'),
    path('apply/<int:order_id>/',views.CouponApplyView.as_view(),name='apply_coupon'),
    
]

A/templates/inc/messages.html
{% if messages %}
{% for msg in messages %}
<p class="alert alert-{{ msg.tags }}">{{ msg }}<p>

{% endfor %}

{% endif %}

A/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark " data-bs-theme="dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Profile</a>
          </li>
          {% if request.user.is_admin %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url "home:bucket" %}">Bucket</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url "accounts:user_logout" %}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url "orders:cart" %}">Cart {{ cart|length }}</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link " href="{% url "accounts:user_login" %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url "accounts:user_register" %}">Register</a>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>